version: '2'
services:
  kiosk:
    restart: always
    build: ./kiosk
    privileged: true
    ports:
      - 8080:8080
  LabsCoordinator:
    restart: always
    build: ./labsCoordinator
    privileged: true
    labels:
      io.balena.features.supervisor-api: 1
